name: backup mysql database
on: [push]
jobs:
  backup-database:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql: [5.6, 5.7, 8]
    container: ubuntu
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ROOT_PASSWORD: db
          MYSQL_DATABASE: db
          MYSQL_USER: db
          MYSQL_PASSWORD: db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      minio:
        image: fclairamb/minio-github-actions
        env:
          MINIO_ACCESS_KEY: 1234567890
          MINIO_SECRET_KEY: 1234567890
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: copy dockerfile
      run: |
        cp -r docker/Dockerfile.mysql.${{ matrix.mysql }} Dockerfile

    - name: create bucket
      run: |
        apt-get update && apt-get install -y wget
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        ./mc config host add s3 http://minio:9000 1234567890 1234567890 --api s3v4
        ./mc mb s3/test

    - name: backup mysql
      uses: ./
      with:
        database_driver: mysql
        database_username: db
        database_password: db
        database_name: db
        database_host: mysql:3306

        storage_driver: s3
        access_key_id: 1234567890
        secret_access_key: 1234567890
        storage_endpoint: minio:9000
        storage_bucket: test
        storage_region: ap-northeast-1
        storage_path: backup

    - name: list buckets and objects
      run: |
        ./mc ls s3/test/backup/
